In [73]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [74]:
data1 = pd.read_csv('1-statsfileinput1.xlsx - Sheet1.csv')
data2 = pd.read_csv('2-statsfileinput2.xlsx - Sheet1.csv')

In [75]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [76]:
df1.head()

CustID  Gender  spending 
0       1       1         18
1       2       2         54
2       3       2         30
3       4       1         78
4       5       2         14

In [77]:
df2.head()

CustID  Gender  spending before marriage   spending after marriage
0       1       1                         18                       50
1       2       2                         54                       47
2       3       2                         30                       33
3       4       1                         78                       32
4       5       2                         14                       46

## Task 1

In [78]:
df1.count()

CustID       83
Gender       83
spending     83
dtype: int64

#### 1.  Two different continuous variable
#### 2. Two different groups
#### Independent sample T-Test

#### H0 : spending of male = spending of female
#### H1 : spending of male != spending of female

In [79]:
df1.rename(columns = {'spending ':'Spending'}, inplace = True)

In [80]:
sample_mean = sum(df1['Spending'])/df1['CustID'].count()
sample_mean

30.27710843373494

In [81]:
male_array =[]
female_array = []
for i in range(df1['Gender'].count()):
    if df1['Gender'][i]==1:
        male_array.append(df1['Spending'][i])
    elif df1['Gender'][i]==2:
        female_array.append(df1['Spending'][i])


In [82]:
mu1 = sum(male_array)/len(male_array)
mu2 = sum(female_array)/len(female_array)
print(mu1,mu2)

32.575 28.13953488372093


In [83]:
print(np.var(male_array), np.var(female_array))

170.794375 111.28285559762034


In [84]:
# here we are having different variance so equal_var = False

result = stats.ttest_ind(a=male_array, b=female_array, equal_var=False)

In [85]:
result.pvalue

0.09849604776250198

In [86]:
result.statistic

1.672994110687672

#### p-value > 0.05 more so we can accept the Null Hypothesis

## Task 2

In [87]:
df2.head()

CustID  Gender  spending before marriage   spending after marriage
0       1       1                         18                       50
1       2       2                         54                       47
2       3       2                         30                       33
3       4       1                         78                       32
4       5       2                         14                       46

#### 1.  Two different continuous variable
#### 2. Two different groups
#### Paired sample T-Test

#### H0 : spending before marriage = spending after marriage
#### H1 : spending before marriage != spending after marriage

In [88]:
before_marriage_array = np.array(df2['spending before marriage '])
before_marriage_array

array([18, 54, 30, 78, 14, 40, 24, 33, 26, 35, 29, 47, 45, 49, 16, 26, 28,
       43, 36, 20, 38, 24, 19, 20, 42, 14, 26, 42, 48, 18, 15, 14, 19, 35,
       48, 17, 50, 37, 28, 27, 37, 23, 22, 47, 46, 33, 24, 13, 25, 13, 31,
       20, 29, 46, 27, 28, 26, 26, 20, 28, 32, 39, 24, 29, 31, 14, 18, 26,
       35, 48, 18, 26, 12, 39, 14, 26, 28, 26, 32, 44, 27, 45, 44],
      dtype=int64)

In [89]:
after_marriage_array = np.array(df2['spending after marriage'])
after_marriage_array

array([50, 47, 33, 32, 46, 29, 19, 48, 48, 24, 38, 30, 39, 32, 42, 42, 50,
       27, 22, 37, 44, 39, 48, 49, 16, 27, 48, 12, 16, 37, 25, 32, 38, 17,
       39, 34, 30, 29, 40, 37, 46, 39, 40, 30, 22, 23, 26, 11, 28, 47, 31,
       40, 14, 13, 34, 32, 13, 40, 34, 10, 14, 12, 42, 30, 15, 47, 39, 22,
       31, 34, 18, 46, 36, 49, 42, 10, 25, 38, 17, 25, 13, 14, 48],
      dtype=int64)

In [90]:
mu1 = sum(before_marriage_array)/len(before_marriage_array)
mu2 = sum(after_marriage_array)/len(after_marriage_array)
print(mu1,mu2)

30.27710843373494 31.710843373493976


In [91]:
print(np.var(before_marriage_array), np.var(after_marriage_array))

144.87501814486865 140.15735230076936


In [92]:
# performing paired sample t test and storing in res variable

In [93]:
res = stats.ttest_rel(a=before_marriage_array, b=after_marriage_array)

In [94]:
res.pvalue

0.4855623119914072

In [95]:
res.statistic

-0.7005574632612455

#### p-value > 0.05 so we can accept the Null Hypothesis

## Task 3 : Using Sample Superstore Dataset

In [133]:
from scipy.stats import f_oneway

In [98]:
sample_sup_orders = pd.read_csv('Sample - Superstore.xls - Orders.csv')

In [100]:
orders_df = pd.DataFrame(sample_sup_orders)
orders_df.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

#### H0 : Sales of segment S1 = Sales of Segment S2 = Sales of Segment S3
#### H1 : At least one difference among the means

#### One way ANOVA since more than two continuous variables 

In [115]:
orders_df['Total_Sales'] = orders_df['Sales']*orders_df['Quantity']
orders_df['Total_Sales'].head()

0     523.9200
1    2195.8200
2      29.2400
3    4787.8875
4      44.7360
Name: Total_Sales, dtype: float64

In [121]:
mean_per_segment = orders_df.groupby('Segment')['Total_Sales'].sum()/orders_df['Sales'].count()
mean_per_segment

Segment
Consumer       582.284111
Corporate      351.821860
Home Office    215.389934
Name: Total_Sales, dtype: float64

In [126]:
consumer_array = []
corporate_array = []
home_office_array = []
for i in range(orders_df['Segment'].count()):
    if orders_df['Segment'][i]=='Consumer':
        consumer_array.append(orders_df['Total_Sales'][i])
    elif orders_df['Segment'][i]=='Corporate':
        corporate_array.append(orders_df['Total_Sales'][i])
    elif orders_df['Segment'][i]=='Home Office':
        home_office_array.append(orders_df['Total_Sales'][i])
print(consumer_array[:5])
print(corporate_array[:5])
print(home_office_array[:5])

[523.92, 2195.82, 4787.8875, 44.736000000000004, 342.02]
[29.24, 136.22, 422.38, 7682.807999999999, 954.5999999999999]
[344.05, 7.632, 88.416, 1019.9519999999999, 1597.1976]


In [127]:
print(len(consumer_array))
print(len(corporate_array))
print(len(home_office_array))

5191
3020
1783


In [130]:
consumer_var = np.var(consumer_array)
corporate_var = np.var(corporate_array)
home_office_var = np.var(home_office_array)
print(consumer_var,corporate_var,home_office_var)

15209488.09286826 12004129.463995013 20568611.41649195


In [131]:
consumer_mean = np.mean(consumer_array)
corporate_mean = np.mean(corporate_array)
home_office_mean = np.mean(home_office_array)
print(consumer_mean,corporate_mean,home_office_mean)

1121.0455405124253 1164.2740637748345 1207.2950075715084


In [135]:
result_anova = f_oneway(consumer_array, corporate_array, home_office_array)

In [136]:
result_anova.pvalue

0.700613068370727

#### Since, pvalue > 0.05 we accept the Null Hypothesis

## Task 4 : Using Chi-Square Test

#### H0 : Segment is related to Category
#### H1 : Segment is not related to category

In [166]:
from scipy.stats import chi2_contingency

In [163]:
data =pd.crosstab(index=orders_df['Segment'],columns=orders_df['Category'], values=orders_df['Total_Sales'], aggfunc='mean')
data

Category       Furniture  Office Supplies   Technology
Segment                                               
Consumer     1845.757470       576.844737  2062.277440
Corporate    1780.880903       633.549805  2188.804987
Home Office  1807.840059       548.407025  2650.402681

In [175]:
res = chi2_contingency(data)
statistic, p_value, degree_of_freedom, expected_values = chi2_contingency(data)

In [176]:
p_value

8.534815798360478e-12

In [178]:
statistic

57.76839431882387

In [179]:
degree_of_freedom

4

In [180]:
expected_values

array([[1729.22226956,  559.64134842, 2196.01602809],
       [1774.85647468,  574.41029313, 2253.96892845],
       [1930.39968828,  624.74992577, 2451.50015166]])

In [185]:
alpha = 0.05
print("p value is " + str(p_value))
if p_value <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (Accept H0)')

p value is 8.534815798360478e-12
Dependent (reject H0)
